#!/usr/bin/env sh
"$(dirname -- "$0")/_/husky.sh"
# npm run test

echo \"[Husky] pre-commit run lint-staged\"

npx lint-staged

echo \"[Husky] pre-commit run npx commitlint\"

npx --no -- commitlint --edit ${1}
